package com.csye6225.fall2018.courseservice.datamodel.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Registrar")
public class Registrar {

	private String registrationId;
	private String offeringId;
	private String offeringType;
	private String department;
	private Integer perUnitPrice;

	public Registrar(String offeringType, String offeringId, String department, Integer perUnitPrice) {
		super();
		this.offeringType = offeringType;
		this.offeringId = offeringId;
		this.department = department;
		this.perUnitPrice = perUnitPrice;
	}

	@DynamoDBHashKey(attributeName = "RegistrationId")
	@DynamoDBAutoGeneratedKey
	public String getRegistrationId() {
		return registrationId;
	}

	public void setRegistrationId(String registrationId) {
		this.registrationId = registrationId;
	}

	@DynamoDBAttribute(attributeName = "OfferingId")
	public String getOfferingId() {
		return offeringId;
	}

	public void setOfferingId(String offeringId) {
		this.offeringId = offeringId;
	}

	@DynamoDBAttribute(attributeName = "OfferingType")
	public String getOfferingType() {
		return offeringType;
	}

	public void setOfferingType(String offeringType) {
		this.offeringType = offeringType;
	}

	@DynamoDBAttribute(attributeName = "Department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName = "PerUnitPrice")
	public Integer getPerUnitPrice() {
		return perUnitPrice;
	}

	public void setPerUnitPrice(Integer perUnitPrice) {
		this.perUnitPrice = perUnitPrice;
	}

	@DynamoDBIgnore
	@Override
	public String toString() {
		return "Registrar [registrationId=" + registrationId + ", offeringId=" + offeringId + ", offeringType="
				+ offeringType + ", department=" + department + ", perUnitPrice=" + perUnitPrice + "]";
	}

}
