package com.csye6225.fall2018.courseservice.datamodel.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Announcements")
public class Announcement {

	private String id;
	private String announcementId;
	private String announcementText;
	private String boardId;

	public Announcement() {
	}

	public Announcement(String announcementText, String boardId) {
		super();
		this.announcementText = announcementText;
		this.boardId = boardId;
	}

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBIndexRangeKey(attributeName = "AnnouncementId", globalSecondaryIndexName = "BoardId-AnnouncementId-index")
	public String getAnnouncementId() {
		return announcementId;
	}

	public void setAnnouncementId(String announcementId) {
		this.announcementId = announcementId;
	}

	@DynamoDBAttribute(attributeName = "AnnouncementText")
	public String getAnnouncementText() {
		return announcementText;
	}

	public void setAnnouncementText(String announcementText) {
		this.announcementText = announcementText;
	}

	@DynamoDBIndexHashKey(attributeName = "BoardId", globalSecondaryIndexName = "BoardId-AnnouncementId-index")
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	@DynamoDBIgnore
	@Override
	public String toString() {
		return "Announcement [id=" + id + ", announcementId=" + announcementId + ", announcementText="
				+ announcementText + ", boardId=" + boardId + "]";
	}

}
